### ISSUE TITLE
"Only send events for identified users" event filter not working as expected

### ISSUE THREAD

**Issue by GriffinAdAuris** [engage-so/posthog-plugin#3]
Hi,

We'd love to use the Posthog+Engage plugin but have found that the identified user filter is not working. We get millions of anonymous users on Posthog every month, which quickly drains our customer allocation on Engage, so we cannot use the Engage platform while this filter isn't functional. We're sadly having to look at some other email platforms because of this small issue, even though Engage was our top choice.

All that we really need in order to use this plugin, is to make sure that customers only get created on Engage if they have an email property attached to their Posthog Person. Alternatively, if we could select certain events to send to Engage, then we could also only send the events that we are interested in from identified users.

I noticed that index.js doesn't use the config.filter var at all. I'm hoping that maybe this could be a quick fix by checking the filter in index.js, but I obviously don't have visibility into your downstream system and if you are handling the filter on https://api.engage.so/posthog. I also want to make sure that this isn't an issue with the way that we have configured our anonymous users and have not fully written off that possibility, so please let me know if this filter is functional based on your tests.

Thanks

**Comment by VeVarunSharma** [comment]
> Hi,
> 
> We'd love to use the Posthog+Engage plugin but have found that the identified user filter is not working. We get millions of anonymous users on Posthog every month, which quickly drains our customer allocation on Engage, so we cannot use the Engage platform while this filter isn't functional. We're sadly having to look at some other email platforms because of this small issue, even though Engage was our top choice.
> 
> All that we really need in order to use this plugin, is to make sure that customers only get created on Engage if they have an email property attached to their Posthog Person.
> 
> I noticed that index.js doesn't use the config.filter var at all. I'm hoping that maybe this could be a quick fix by checking the filter in index.js, but I obviously don't have visibility into your downstream system and if you are handling the filter on https://api.engage.so/posthog. I also want to make sure that this isn't an issue with the way that we have configured our anonymous users and have not fully written off that possibility, so please let me know if this filter is functional based on your tests.
> 
> Thanks

+1 on this issue. Great context here. Thanks for sharing this @GriffinAdAuris! 🙌🏽

**Comment by VeVarunSharma** [comment]
> Hi,
> 
> We'd love to use the Posthog+Engage plugin but have found that the identified user filter is not working. We get millions of anonymous users on Posthog every month, which quickly drains our customer allocation on Engage, so we cannot use the Engage platform while this filter isn't functional. We're sadly having to look at some other email platforms because of this small issue, even though Engage was our top choice.
> 
> All that we really need in order to use this plugin, is to make sure that customers only get created on Engage if they have an email property attached to their Posthog Person.
> 
> I noticed that index.js doesn't use the config.filter var at all. I'm hoping that maybe this could be a quick fix by checking the filter in index.js, but I obviously don't have visibility into your downstream system and if you are handling the filter on https://api.engage.so/posthog. I also want to make sure that this isn't an issue with the way that we have configured our anonymous users and have not fully written off that possibility, so please let me know if this filter is functional based on your tests.
> 
> Thanks

@kehers  @bytemerger  Thoughts on this? We'd love to know how you folks are thinking about this

**Comment by GriffinAdAuris** [comment]
This was resolved over an email thread. Thanks team!

**Comment by kehers** [comment]
Thanks @GriffinAdAuris @ve-varun-sharma. Happy to have resolved this.
